Adds DICOM_File_Region_Reader & Test
GoogleCloudPlatform/wsi-to-dicom-converter pull request #62
Opened 2021-09-15 17:00 UTC by Philbrick

DICOM_File_Region_Reader adds functionality similar to openslide_read_region.

Method enables caller to retrieve an arbitrary 2D patch of bytes from the uncompressed frames stored in one or more DcmFileDrafts and multiple frames.
Assumes frames have same dimensions in all DcmFileDraft Files.  If patch extends beyond image bounds sets pixel values for region outside the patch to 0.

Adds unit tests.

2021-09-15 18:27 UTC, danielbeaudreau reviewed
/gcbrun

2021-09-15 18:27 UTC, danielbeaudreau commented on src/dicom_file_region_reader.h
> +  // DICOMFrileFrameRegionReader.
typo

2021-09-15 19:14 UTC, danielbeaudreau commented
/gcbrun

2021-09-15 21:01 UTC, danielbeaudreau requested changes

2021-09-15 21:01 UTC, danielbeaudreau commented on src/dicom_file_region_reader.h
> +  //   layer_Y : upper right Y coordinate in image coordinates.
nit: shouldn't it be left rather than right? same elsewhere in these files

2021-09-15 21:01 UTC, danielbeaudreau commented on src/dicom_file_region_reader.cpp
> +    // If memory extends beyond file space. Writes in for memory pixel data
This comment is not clear

2021-09-15 21:01 UTC, danielbeaudreau commented on tests/dicom_file_region_reader.cpp
> +    ASSERT_FALSE(region_reader.read_region(0, 0, 1, 1, mem));
indent

2021-09-15 21:15 UTC, Philbrick commented on src/dicom_file_region_reader.h
> +  //   layer_Y : upper right Y coordinate in image coordinates.
Yes, Thanks!

2021-09-15 21:16 UTC, Philbrick commented on tests/dicom_file_region_reader.cpp
> +    ASSERT_FALSE(region_reader.read_region(0, 0, 1, 1, mem));
fixed.

2021-09-15 21:25 UTC, Philbrick commented on tests/dicom_file_region_reader.cpp
> +    ASSERT_FALSE(region_reader.read_region(0, 0, 1, 1, mem));
fixed

2021-09-15 21:25 UTC, Philbrick commented on src/dicom_file_region_reader.cpp
> +    // If memory extends beyond file space. Writes in for memory pixel data
fixed

2021-09-16 13:40 UTC, danielbeaudreau commented
/gcbrun

2021-09-16 14:30 UTC, danielbeaudreau approved these changes

2021-09-16 14:30 UTC, merged