Refactor downsampling level dimension code
GoogleCloudPlatform/wsi-to-dicom-converter pull request #69
Opened 2021-09-28 16:46 UTC by Philbrick

Refactor downsampling level dimension code to function.
- Change 2/3 for cropping refactor
- No change in behavior

2021-09-28 17:57 UTC, danielbeaudreau commented
/gcbrun

2021-09-28 19:32 UTC, danielbeaudreau requested changes

2021-09-28 19:32 UTC, danielbeaudreau commented on src/wsiToDcm.cpp
> +                                  SlideLevelDim * smallestSlideLevel) {
smallestSlideLevel param is unused here

2021-09-28 19:32 UTC, danielbeaudreau commented on src/wsiToDcm.cpp
> +      }
Should we be validating somewhere that downsample ints are specified in ascending order when progressive mode is enabled? Or maybe just documenting in the comment of that flag that this code path won't run unless downsamples are specified in an increasing order

2021-09-28 21:38 UTC, Philbrick commented on src/wsiToDcm.cpp
> +                                  SlideLevelDim * smallestSlideLevel) {
Removed.

2021-09-29 13:51 UTC, danielbeaudreau commented
/gcbrun

2021-09-29 14:22 UTC, merged